const MATERIALS={display:{label:'Display',options:[300]},pouch2pk:{label:'Pouch 2PK',options:[2400]},pouch3pk:{label:'Pouch 3PK',options:[3000,2400]}};
const $=id=>document.getElementById(id);const fmt=n=>Math.round(Number(n)||0).toLocaleString('es-DO');const num=v=>Math.max(0,Math.floor(Number(v)||0));
let lines=[];
function uid(){return Math.random().toString(36).slice(2,10)}
function newLine(material='display'){return{id:uid(),material,unitsPerBox:MATERIALS[material].options[0],declaredBoxes:'',receivedBoxes:'',notes:''}}
function calc(l){const d=num(l.declaredBoxes),r=num(l.receivedBoxes),u=num(l.unitsPerBox),du=d*u,ru=r*u,diff=ru-du;return{d,r,u,du,ru,diff,status:diff===0?'CUADRA':diff<0?'FALTANTE':'SOBRANTE'}}
function statusClass(s){return s==='CUADRA'?'ok':s==='FALTANTE'?'missing':'extra'}
function render(){const wrap=$('lines');wrap.innerHTML='';lines.forEach((l,i)=>{const c=calc(l),div=document.createElement('div');div.className='line';
const opts=Object.entries(MATERIALS).map(([k,v])=>`<option value="${k}" ${l.material===k?'selected':''}>${v.label}</option>`).join('');
const packOpts=MATERIALS[l.material].options.map(x=>`<option value="${x}" ${Number(l.unitsPerBox)===x?'selected':''}>${fmt(x)}</option>`).join('');
div.innerHTML=`<div><div class="mini">Material</div><select data-k="material" data-i="${i}">${opts}</select></div><div><div class="mini">Unid./caja</div><select data-k="unitsPerBox" data-i="${i}">${packOpts}</select></div><div><div class="mini">Cajas NTM</div><input data-k="declaredBoxes" data-i="${i}" type="number" min="0" value="${l.declaredBoxes}" placeholder="0"></div><div><div class="mini">Cajas recibidas</div><input data-k="receivedBoxes" data-i="${i}" type="number" min="0" value="${l.receivedBoxes}" placeholder="0"></div><div><div class="mini">Unid. NTM</div><div class="calc">${fmt(c.du)}</div></div><div><div class="mini">Unid. recibidas</div><div class="calc">${fmt(c.ru)}</div></div><button class="btn danger remove" data-remove="${i}" type="button">Eliminar</button><div class="full"><div class="mini">Resultado</div><div class="status-box" style="margin-top:0;padding:10px 12px"><span>Diferencia: <b>${c.diff>0?'+':''}${fmt(c.diff)}</b> unidades</span><span class="status-pill ${statusClass(c.status)}">${c.status}</span></div></div><div class="full"><div class="mini">Nota de esta línea</div><input data-k="notes" data-i="${i}" value="${l.notes||''}" placeholder="Opcional"></div>`;wrap.appendChild(div)});
wrap.querySelectorAll('[data-k]').forEach(el=>el.addEventListener('input',e=>{const i=+e.target.dataset.i,k=e.target.dataset.k;if(k==='material'){lines[i].material=e.target.value;lines[i].unitsPerBox=MATERIALS[e.target.value].options[0]}else lines[i][k]=e.target.value;render();save(false)}));
wrap.querySelectorAll('[data-remove]').forEach(el=>el.addEventListener('click',e=>{lines.splice(+e.currentTarget.dataset.remove,1);if(!lines.length)lines=[newLine()];render();save(false)}));updateSummary()}
function totals(){const cs=lines.map(calc);return{declaredBoxes:cs.reduce((a,c)=>a+c.d,0),receivedBoxes:cs.reduce((a,c)=>a+c.r,0),declaredUnits:cs.reduce((a,c)=>a+c.du,0),receivedUnits:cs.reduce((a,c)=>a+c.ru,0),diff:cs.reduce((a,c)=>a+c.diff,0),cs}}
function updateSummary(){const t=totals();$('sumDeclaredBoxes').textContent=fmt(t.declaredBoxes);$('sumReceivedBoxes').textContent=fmt(t.receivedBoxes);$('sumDeclaredUnits').textContent=fmt(t.declaredUnits);$('sumReceivedUnits').textContent=fmt(t.receivedUnits);$('sumDiff').textContent=(t.diff>0?'+':'')+fmt(t.diff);const st=t.diff===0?'CUADRA':t.diff<0?'FALTANTE':'SOBRANTE';$('overallStatus').textContent=st;$('overallStatus').className='status-pill '+statusClass(st);$('sumDiff').style.color=st==='CUADRA'?'var(--green)':st==='FALTANTE'?'var(--danger)':'var(--warn)';
$('materialSummary').innerHTML=Object.entries(MATERIALS).map(([id,m])=>{const rel=lines.map((l,i)=>({l,c:t.cs[i]})).filter(x=>x.l.material===id);const db=rel.reduce((a,x)=>a+x.c.d,0),rb=rel.reduce((a,x)=>a+x.c.r,0),du=rel.reduce((a,x)=>a+x.c.du,0),ru=rel.reduce((a,x)=>a+x.c.ru,0);return`<div class="mat"><b>${m.label}</b><span>NTM: ${fmt(db)} cajas · ${fmt(du)} unid.<br>Recibido: ${fmt(rb)} cajas · ${fmt(ru)} unid.<br>Diferencia: ${(ru-du)>0?'+':''}${fmt(ru-du)} unid.</span></div>`}).join('')}
function reportData(){return{fecha:$('fecha').value,hora:$('hora').value,turno:$('turno').value,area:$('area').value,recibido:$('recibido').value,despachado:$('despachado').value,referencia:$('referencia').value,numero:$('numero').value,observaciones:$('observaciones').value,lines}}
function save(show=true){localStorage.setItem('recepcionNTM',JSON.stringify(reportData()));if(show)toast('Borrador guardado en este dispositivo.')}
function load(){let d;try{d=JSON.parse(localStorage.getItem('recepcionNTM')||'null')}catch{}if(!d){const now=new Date(),p=n=>String(n).padStart(2,'0');$('fecha').value=`${now.getFullYear()}-${p(now.getMonth()+1)}-${p(now.getDate())}`;$('hora').value=`${p(now.getHours())}:${p(now.getMinutes())}`;lines=[newLine()];return}['fecha','hora','turno','area','recibido','despachado','referencia','numero','observaciones'].forEach(k=>{if($(k)&&d[k]!=null)$(k).value=d[k]});lines=Array.isArray(d.lines)&&d.lines.length?d.lines:[newLine()]}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function cleanText(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[–—]/g,'-').replace(/[^\x20-\x7E]/g,'')}
function escPdf(s){return cleanText(s).replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)')}
function makePdfBlob(){const d=reportData(),t=totals(),rows=[];rows.push(['REPORTE DE RECIBIMIENTO DE MATERIALES NTM']);rows.push([`Fecha: ${d.fecha||'-'}   Hora: ${d.hora||'-'}   Turno: ${d.turno||'-'}`]);rows.push([`Area/Modulo: ${d.area||'-'}`]);rows.push([`Recibido por: ${d.recibido||'-'}`]);rows.push([`Despachado por NTM: ${d.despachado||'-'}`]);rows.push([`Vale/Referencia: ${d.referencia||'-'}   No.: ${d.numero||'-'}`]);rows.push(['']);rows.push(['DETALLE']);lines.forEach((l,i)=>{const c=calc(l);rows.push([`${i+1}. ${MATERIALS[l.material].label} | ${fmt(c.u)} unid/caja`]);rows.push([`   NTM: ${fmt(c.d)} cajas = ${fmt(c.du)} unid. | Recibido: ${fmt(c.r)} cajas = ${fmt(c.ru)} unid.`]);rows.push([`   Diferencia: ${c.diff>0?'+':''}${fmt(c.diff)} unid. | Estado: ${c.status}${l.notes?' | Nota: '+l.notes:''}`])});rows.push(['']);rows.push([`TOTALES: NTM ${fmt(t.declaredUnits)} unid. | Recibido ${fmt(t.receivedUnits)} unid.`]);rows.push([`DIFERENCIA TOTAL: ${t.diff>0?'+':''}${fmt(t.diff)} unid. | ${t.diff===0?'CUADRA':t.diff<0?'FALTANTE':'SOBRANTE'}`]);if(d.observaciones)rows.push(['Observaciones: '+d.observaciones]);rows.push(['']);rows.push(['Firma recibido: ____________________    Firma NTM: ____________________']);
let y=800,content='BT\n/F1 16 Tf\n50 800 Td\n';rows.forEach((r,idx)=>{const text=escPdf(r[0]);const size=idx===0?16:(r[0]==='DETALLE'?12:10);if(idx>0)y-=idx===7?24:18;content+=`ET\nBT\n/F1 ${size} Tf\n50 ${y} Td\n(${text.slice(0,110)}) Tj\n`});content+='ET';const objs=[];objs[1]='<< /Type /Catalog /Pages 2 0 R >>';objs[2]='<< /Type /Pages /Kids [3 0 R] /Count 1 >>';objs[3]='<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>';objs[4]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';objs[5]=`<< /Length ${content.length} >>\nstream\n${content}\nendstream`;let pdf='%PDF-1.4\n',offs=[0];for(let i=1;i<=5;i++){offs[i]=pdf.length;pdf+=`${i} 0 obj\n${objs[i]}\nendobj\n`}const xref=pdf.length;pdf+='xref\n0 6\n0000000000 65535 f \n';for(let i=1;i<=5;i++)pdf+=String(offs[i]).padStart(10,'0')+' 00000 n \n';pdf+=`trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return new Blob([pdf],{type:'application/pdf'})}
function filename(){const d=reportData();return`Recepcion_NTM_${d.fecha||'sin-fecha'}_${(d.numero||'reporte').replace(/[^a-z0-9_-]/gi,'_')}.pdf`}
function downloadPdf(){const blob=makePdfBlob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename();a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('PDF generado.')}
async function shareReport(){const blob=makePdfBlob(),file=new File([blob],filename(),{type:'application/pdf'});try{if(navigator.canShare&&navigator.canShare({files:[file]})){await navigator.share({title:'Recepción NTM',text:'Reporte de recibimiento de materiales NTM',files:[file]});return}if(navigator.share){await navigator.share({title:'Recepción NTM',text:`Reporte NTM ${$('fecha').value}. Diferencia total: ${fmt(totals().diff)} unidades.`});return}downloadPdf()}catch(e){if(e&&e.name!=='AbortError')downloadPdf()}}
$('addLine').addEventListener('click',()=>{lines.push(newLine());render();save(false)});$('pdfBtn').addEventListener('click',downloadPdf);$('shareBtn').addEventListener('click',shareReport);$('saveBtn').addEventListener('click',()=>save(true));$('clearBtn').addEventListener('click',()=>{if(confirm('¿Crear un recibimiento nuevo y borrar el borrador actual?')){localStorage.removeItem('recepcionNTM');location.reload()}});['fecha','hora','turno','area','recibido','despachado','referencia','numero','observaciones'].forEach(k=>$(k).addEventListener('input',()=>save(false)));load();render();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));